config/routes.rb
Rails.application.routes.draw do

  get 'sign_up' => 'users#new'

  root 'sample#home'

  get 'sample/about'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'account_activations/:id/edit' => 'account_activations#edit', as: 'edit_account_activations'
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]

end

app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feeds.paginate(page: params[:page])
    end
  end

  def about
  end

  def destroy
  end
end

app/helpers/sample_helper.rb
module SampleHelper
end

app/views/sample/about.html.erb
<h1>Sample#about</h1>
<p>Find me in app/views/sample/about.html.erb</p>

app/views/sample/home.html.erb
<% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
    
<% else %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

    <%= link_to "Sign up now!", sign_up_path, class: "btn btn-lg btn-primary" %>

</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<%end%>